; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26430.0 

	TITLE	G:\Users\Administrator\Desktop\sys_programming\2015440159±èÁ¤¿ë\20180921hw1\ptrsum.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?ptrsum@@YGXPAH00@Z				; ptrsum
PUBLIC	_main
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	___security_cookie:DWORD
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File g:\users\administrator\desktop\sys_programming\2015440159±èÁ¤¿ë\20180921hw1\ptrsum.cpp
;	COMDAT _main
_TEXT	SEGMENT
_c$ = -36						; size = 4
_b$ = -24						; size = 4
_a$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_main	PROC						; COMDAT

; 5    : int main(void) {

	push	ebp
	mov	ebp, esp
	sub	esp, 232				; 000000e8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-232]
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax

; 6    : 
; 7    : 	int a, b, c;
; 8    : 	a = 10;

	mov	DWORD PTR _a$[ebp], 10			; 0000000aH

; 9    : 	b = 20;

	mov	DWORD PTR _b$[ebp], 20			; 00000014H

; 10   : 	ptrsum(&a, &b, &c);

	lea	eax, DWORD PTR _c$[ebp]
	push	eax
	lea	ecx, DWORD PTR _b$[ebp]
	push	ecx
	lea	edx, DWORD PTR _a$[ebp]
	push	edx
	call	?ptrsum@@YGXPAH00@Z			; ptrsum

; 11   : 
; 12   : 	return 0;

	xor	eax, eax

; 13   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN7@main
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 232				; 000000e8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
$LN7@main:
	DD	3
	DD	$LN6@main
$LN6@main:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN3@main
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN4@main
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN5@main
$LN5@main:
	DB	99					; 00000063H
	DB	0
$LN4@main:
	DB	98					; 00000062H
	DB	0
$LN3@main:
	DB	97					; 00000061H
	DB	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File g:\users\administrator\desktop\sys_programming\2015440159±èÁ¤¿ë\20180921hw1\ptrsum.cpp
;	COMDAT ?ptrsum@@YGXPAH00@Z
_TEXT	SEGMENT
_p1$ = 8						; size = 4
_p2$ = 12						; size = 4
_p3$ = 16						; size = 4
?ptrsum@@YGXPAH00@Z PROC				; ptrsum, COMDAT

; 15   : void WINAPI ptrsum(int *p1, int *p2, int *p3) {

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 16   : 
; 17   : 	*p3 = *p1 + *p2;

	mov	eax, DWORD PTR _p1$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR _p2$[ebp]
	add	ecx, DWORD PTR [edx]
	mov	eax, DWORD PTR _p3$[ebp]
	mov	DWORD PTR [eax], ecx

; 18   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?ptrsum@@YGXPAH00@Z ENDP				; ptrsum
_TEXT	ENDS
END
